export enum StockMovementReason {
  SALE = -1,
  PURCHASE = 1,
  TRANSFER = 1000,
  RETURN_SUPPLIER = -2,
  RETURN_CUSTOMER = 2,
  BREAKAGE = -3,
  ADJUSTMENT_ADD = 4,
  ADJUSTMENT_MINUS = -4,
  SAMPLE_OUT = -5,
  FREE = -6,
  USED_ITEM = -7,
  RECTIFY_ERROR = -8
}